import assert from "node:assert/strict";
import { readFile, writeFile } from "node:fs/promises";

const root = new URL("../", import.meta.url);
const schema = JSON.parse(await readFile(new URL("reverse-command-v1/schema.json", root), "utf8"));
const fixtures = JSON.parse(await readFile(new URL("reverse-command-v1/fixtures.json", root), "utf8"));
const output = new URL("src/generated/reverseCommandV1.ts", root);

assert.equal(schema.$id, "urn:rnm-dev:protocol:reverse-command-v1");
assert.equal(fixtures.capability, schema.$defs.command.properties.capability.const);
assert.deepEqual(
  fixtures.enabledOperations,
  schema.$defs.command.properties.operation.enum ?? [],
  "fixtures and schema must declare the same operation union",
);

const statuses = schema.$defs.commandResult.properties.status.enum;
const acceptedStates = schema.$defs.commandAccepted.properties.state.enum;
const commandStates = schema.$defs.commandStatus.properties.state.enum;
const priorities = schema.$defs.durableCommandResult.properties.priority.enum;
const union = (values) => values.map((value) => JSON.stringify(value)).join(" | ") || "never";

const generated = `// Generated by scripts/generate.mjs. Do not edit by hand.

export const REVERSE_COMMAND_CAPABILITY = ${JSON.stringify(fixtures.capability)} as const;
export const REVERSE_COMMAND_MAX_FRAME_BYTES = ${fixtures.maxCommandFrameBytes} as const;
export const REVERSE_COMMAND_OPERATIONS = ${JSON.stringify(fixtures.enabledOperations)} as const;

export type ReverseCommandOperation = typeof REVERSE_COMMAND_OPERATIONS[number];
export type ReverseCommandResultStatus = ${union(statuses)};
export type ReverseCommandAcceptedState = ${union(acceptedStates)};
export type ReverseCommandStatusState = ${union(commandStates)};
export type DurableMessagePriority = ${union(priorities)};

export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };
export type JsonObject = { [key: string]: JsonValue };

export interface ReverseCommandActor {
  userId: string;
  email: string;
}

export interface ReverseCommandTarget {
  peonId: string;
  sessionId?: string;
  projectId?: string;
  transferId?: string;
}

export interface ReverseCommandEnvelope {
  type: "command";
  protocol: 1;
  capability: typeof REVERSE_COMMAND_CAPABILITY;
  commandId: string;
  operation: ReverseCommandOperation;
  target: ReverseCommandTarget;
  actor: ReverseCommandActor;
  payload: JsonObject;
  expected?: JsonObject | null;
  requestedAt: number;
}

export interface ReverseCommandAcceptedFrame {
  type: "command_accepted";
  protocol: 1;
  commandId: string;
  operation: ReverseCommandOperation;
  state: ReverseCommandAcceptedState;
  replayed: boolean;
  acceptedAt: number;
}

export interface ReverseCommandResultFrame {
  type: "command_result";
  protocol: 1;
  commandId: string;
  operation: ReverseCommandOperation;
  status: ReverseCommandResultStatus;
  code: string;
  message?: string;
  completedAt: number;
  result: JsonObject | null;
}

export interface ReverseCommandStatusFrame {
  type: "command_status";
  protocol: 1;
  commandId: string;
  state: ReverseCommandStatusState;
  result?: ReverseCommandResultFrame;
}

export interface DurableReverseCommandResult {
  type: "durable_message";
  epoch: string;
  cursor: string;
  messageId: string;
  priority: DurableMessagePriority;
  capability: typeof REVERSE_COMMAND_CAPABILITY;
  payload: ReverseCommandResultFrame;
}
`;

if (process.argv.includes("--check")) {
  const current = await readFile(output, "utf8").catch(() => "");
  assert.equal(current, generated, "generated reverse-command-v1 TypeScript is stale; run npm run generate");
} else {
  await writeFile(output, generated);
}
