// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter/services.dart' show appFlavor;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return appFlavor == 'dev' ? androidDev : android;
      case TargetPlatform.iOS:
        return appFlavor == 'dev' ? iosDev : ios;
      case TargetPlatform.macOS:
        return appFlavor == 'dev' ? macosDev : macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDraueVsKqZmHnMTTrfsEeeHeb9u2fEpR0',
    appId: '1:982158645364:web:4af883b857fc8432a41921',
    messagingSenderId: '982158645364',
    projectId: 'overseer-9fe46',
    authDomain: 'overseer-9fe46.firebaseapp.com',
    storageBucket: 'overseer-9fe46.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY-Eb2m2bWF-vg607y62Hz_Zjlf4q6wgw',
    appId: '1:982158645364:android:e208c9039c8b3ab5a41921',
    messagingSenderId: '982158645364',
    projectId: 'overseer-9fe46',
    storageBucket: 'overseer-9fe46.firebasestorage.app',
  );

  static const FirebaseOptions androidDev = FirebaseOptions(
    apiKey: 'AIzaSyB425FbG3ljt-fvRMFPn-fLm4DRazIMrH8',
    appId: '1:713631882904:android:b68a3166a0dc7d77647aed',
    messagingSenderId: '713631882904',
    projectId: 'overseer-dev-f24fe',
    storageBucket: 'overseer-dev-f24fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEZKluWUR1rx2B5XiuOE6C_3fx6Djbco0',
    appId: '1:982158645364:ios:39d4f53fd26d435ea41921',
    messagingSenderId: '982158645364',
    projectId: 'overseer-9fe46',
    storageBucket: 'overseer-9fe46.firebasestorage.app',
    iosBundleId: 'org.ovrseer.app',
  );

  static const FirebaseOptions iosDev = FirebaseOptions(
    apiKey: 'AIzaSyB6LAvLd3qdRI38SW-oiajtrP_KCksvVso',
    appId: '1:713631882904:ios:87af605a6bbd5f1a647aed',
    messagingSenderId: '713631882904',
    projectId: 'overseer-dev-f24fe',
    storageBucket: 'overseer-dev-f24fe.firebasestorage.app',
    iosBundleId: 'org.ovrseer.app.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEZKluWUR1rx2B5XiuOE6C_3fx6Djbco0',
    appId: '1:982158645364:ios:39d4f53fd26d435ea41921',
    messagingSenderId: '982158645364',
    projectId: 'overseer-9fe46',
    storageBucket: 'overseer-9fe46.firebasestorage.app',
    iosBundleId: 'org.ovrseer.app',
  );

  static const FirebaseOptions macosDev = FirebaseOptions(
    apiKey: 'AIzaSyB6LAvLd3qdRI38SW-oiajtrP_KCksvVso',
    appId: '1:713631882904:ios:87af605a6bbd5f1a647aed',
    messagingSenderId: '713631882904',
    projectId: 'overseer-dev-f24fe',
    storageBucket: 'overseer-dev-f24fe.firebasestorage.app',
    iosBundleId: 'org.ovrseer.app.dev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDraueVsKqZmHnMTTrfsEeeHeb9u2fEpR0',
    appId: '1:982158645364:web:13db7cc020b7cc44a41921',
    messagingSenderId: '982158645364',
    projectId: 'overseer-9fe46',
    authDomain: 'overseer-9fe46.firebaseapp.com',
    storageBucket: 'overseer-9fe46.firebasestorage.app',
  );
}
