import 'package:flutter/material.dart';

/// The Overseer product mark with consistent sizing and accessibility.
class OverseerLogo extends StatelessWidget {
  const OverseerLogo({super.key, this.size = splashExtent, this.imageProvider});

  /// Matches the 1x native launch image generated by flutter_native_splash.
  static const double splashExtent = 288;
  static const String assetPath = 'assets/images/overseer-splash.png';

  final double size;

  /// Allows callers such as tests and previews to provide another image source.
  final ImageProvider<Object>? imageProvider;

  @override
  Widget build(BuildContext context) {
    return Semantics(
      image: true,
      label: 'Overseer',
      child: Image(
        image: imageProvider ?? const AssetImage(assetPath),
        width: size,
        height: size,
        fit: BoxFit.contain,
        excludeFromSemantics: true,
        filterQuality: FilterQuality.high,
      ),
    );
  }
}
